
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-happycows
owner: ucsb-cs156
repo_name: proj-happycows
pull_requests: [{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/add-script-set-node-version","number":231,"title":"Add script to set node version from package.json","url":"https://github.com/ucsb-cs156/proj-happycows/pull/231"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s26-16","number":229,"title":"S26 16","url":"https://github.com/ucsb-cs156/proj-happycows/pull/229"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s26-15","number":228,"title":"S26 15","url":"https://github.com/ucsb-cs156/proj-happycows/pull/228"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s26-13","number":227,"title":"S26 13","url":"https://github.com/ucsb-cs156/proj-happycows/pull/227"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s26-14","number":226,"title":"S26 14","url":"https://github.com/ucsb-cs156/proj-happycows/pull/226"}]
