
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-happycows
owner: ucsb-cs156
repo_name: proj-happycows
pull_requests: [{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/add-activity-button-on-list-games-page","number":303,"title":"Add game-wide Activity page for course-linked games","url":"https://github.com/ucsb-cs156/proj-happycows/pull/303"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/add-capacity-component-to-dashboard","number":301,"title":"Add \"Capacity\" dashboard section (Total Cows, Eff Cap, % of Carrying Capacity, Avg Cow Health, Avg Cows/Farmer)","url":"https://github.com/ucsb-cs156/proj-happycows/pull/301"}]
