# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "12-backend-jacoco: Java Test Coverage (Jacoco)"

on:
  workflow_dispatch:
  pull_request:
    paths: [src/**, pom.xml, lombok.config, .github/workflows/12-backend-jacoco.yml]
  push:
    branches: [ main ]
    paths: [src/**, pom.xml, lombok.config, .github/workflows/12-backend-jacoco.yml]

jobs:
  call-backend-jacoco:
    uses: ucsb-cs156/workflows/.github/workflows/12-backend-jacoco.yml@main
    with:
      JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 


  